### ISSUE TITLE
Get Started - Profile - email required but no email field

### ISSUE THREAD

**Issue by gregoryfoster** [CannabisData/cannabisdata#3]
1. On initial sign in, prompted to "[Create your profile](http://127.0.0.1:8000/get-started/profile)"
2. There is guidance to "Initialize your account, an email is required."  No email field is displayed, and you can't progress to the next step.

**Comment by gregoryfoster** [comment]
Since an email address is required to sign up, probably shouldn't prompt to replicate that information.  At a minimum, include it as the default value (but at potential risk of confusing matters on sign in).

**Comment by keeganskeate** [comment]
This field was meant to be populated, a small correction and the user profile form (on the `/settings/user` page) is now working as expected. Perhaps we can talk more about what would make a good getting started section, because at the moment it is sparse enough that I think we can contain this functionality neatly elsewhere and have the user jump right into the data on the dashboard.

**Comment by gregoryfoster** [comment]
This looks good, thank you!  We'll talk more about the new user flow.
